### ISSUE TITLE
Error: Invalid JSON RPC response: ""

### ISSUE THREAD

**Issue by michael-spengler** [distributed-ledger-technology/web3#24]
<img width="1442" alt="Screenshot 2021-12-10 at 11 44 31" src="https://user-images.githubusercontent.com/43786652/145561620-964dc4c9-7f88-4761-b622-97e1760b2b60.png">

@ntrotner: Do you have a quick fix for this?

**Comment by ntrotner** [comment]
either the permission is missing to make create an internet connection or the node url isn't valid

**Comment by michael-spengler** [comment]
thank you Nikita --> adding the --allow-net flag solved the issue.
