### ISSUE TITLE
Missing npm module when using web3 in Fresh

### ISSUE THREAD

**Issue by bkosm** [distributed-ledger-technology/web3#39]
Hey, when trying out the module I get the following error:

```
✘ [ERROR] [plugin deno] specifier was a bare specifier, but was not remapped to anything by importMap.

    deno:https://deno.land/x/web3@v0.9.2/packages/web3-providers-ws/src/helpers.js:10:22:
      10 │   const url = require('url');
         ╵                       ~~~~~
```

I was looking for a module equivalent in Deno to patch it through `import_map.json`, but found none.

---

The exact snippet causing the issue is: 
```tsx
import { useEffect, useState } from "preact/hooks";
import Web3 from "https://deno.land/x/web3@v0.11.1/mod.ts";

export function useWeb3(): { web3?: Web3 } {
  const [web3, setWeb3] = useState<Web3 | undefined>(undefined);

  useEffect(() => {
    const eth = window.ethereum;

    if (!eth) {
      console.error("No web3 provider found");
    } else {
      setWeb3(new Web3(eth));
    }
  }, []);

  return { web3 };
}

```
---

I'm having issues with `ethers` library via skypack (missing types, clunky api) and I'd really be happy with going around this issue and using `Web3`. Do you have any ideas?

**Comment by bkosm** [comment]
It looks like a bug with the following lines: 

https://github.com/distributed-ledger-technology/web3/blob/0fd65c6ce59d77bc31979dca00afb7cf2806cb02/packages/web3-providers-ws/src/helpers.js#L1-L2

Even though I'm using Fresh framework for Deno, it evaluates `isNode || isRN` to `true` for my setup. The one for `isNode` is likely the culprit as it is complex and I have no idea what's it about 😅

**Comment by bkosm** [comment]
I ran:
```ts
console.log({
  isRN:
    typeof navigator !== "undefined" && navigator.product === "ReactNative",
  isNode:
    Object.prototype.toString.call(
      typeof process !== "undefined" ? process : 0
    ) === "[object process]",
});
```
Both within `main.ts` of Fresh boilerplate and within a `useEffect` of an island (client side).
Both return false in either case 😩

**Comment by ChristianOConnor** [comment]
@bkosm I am having this exact error too. Any fixes?  

Here is my exact offending code:  
```
/** @jsx h */
import { h } from "preact";
import { useState } from "preact/hooks";
import { tw } from "@twind";
import { Button } from "../components/Button1.tsx";
import Web3 from "web3"

interface MetamaskProps {
    start: string;
}

export default function Metamask(props: MetamaskProps) {
    const [count, setCount] = useState(props.start);
    async function getMetamaskBalance() {
        const providerURL = "https://rinkeby.infura.io/v3/<MY KEY HERE>";
        const web3 = new Web3(new Web3.providers.HttpProvider(providerURL));
        const balance = await web3.eth.getBalance("<MY ETH ADDRESS HERE>")
        setCount(balance.toString());
    }
    return (
        <div class={tw`flex gap-2 w-full`}>
            <p class={tw`flex-grow-1 font-bold text-xl`}>{count}</p>
            <Button onClick={getMetamaskBalance}>Get Balance</Button>
    </div>
    );
}
```  

and my import map looks like this:  
```
{
  "imports": {
    "$fresh/": "https://deno.land/x/fresh@1.0.2/",
    "preact": "https://esm.sh/preact@10.10.0",
    "preact/": "https://esm.sh/preact@10.10.0/",
    "preact-render-to-string": "https://esm.sh/preact-render-to-string@5.2.1?external=preact",
    "@twind": "./utils/twind.ts",
    "twind": "https://esm.sh/twind@0.16.17",
    "twind/": "https://esm.sh/twind@0.16.17/",
    "web3": "https://deno.land/x/web3/mod.ts"
  }
}
```  

Is there any workaround or something I'm doing wrong?  

This is my error btw:  
```
An error occurred during route handling or page rendering. Error: Build failed with 1 error:
deno:https://deno.land/x/web3@v0.9.2/packages/web3-providers-ws/src/helpers.js:10:22: ERROR: [plugin: deno] specifier was a bare specifier, but was not remapped to anything by importMap.
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.51/mod.js:1601:15)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1243:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.51/mod.js:1023:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.51/mod.js:1241:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1354:14
    at https://deno.land/x/esbuild@v0.14.51/mod.js:655:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.51/mod.js:752:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.51/mod.js:621:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1880:11
```

**Comment by bkosm** [comment]
@ChristianOConnor I can't think of any solution without changing the source, so I'm waiting for the maintainers to respond.

**Comment by ChristianOConnor** [comment]
@bkosm Gotcha, are there any other deno packages that provide the same service? Just in the short term while we wait for a path. Is there a Deno port for Ethers?

**Comment by bkosm** [comment]
@ChristianOConnor you can try with `ethers` from skypack, but I remember I had a rough time:

```ts
import ethers from 'https://cdn.skypack.dev/ethers?dts'
```

LMK if it worked for you!

**Comment by ChristianOConnor** [comment]
@bkosm I ended up adding `"ethers": "https://cdn.ethers.io/lib/ethers-5.2.esm.min.js"` to `import_map.json` and calling it with `import { ethers, providers } from "ethers";`. This has been working for me.

**Comment by bkosm** [comment]
@ChristianOConnor feel free to reference some of your example code here for others until the issue is resolved:)

**Comment by ChristianOConnor** [comment]
I'm currently writing a `fresh` app and I have this island that gets the balance of an address. The function is called `Metamask` but it doesn't have Metamask functionality yet.  
```
/** @jsx h */
import { h } from "preact";
import { useState } from "preact/hooks";
import { tw } from "@twind";
import { Button } from "../components/Button1.tsx";
import { ethers, providers } from "ethers";

interface MetamaskProps {
    start: string;
    prviderURL: string;
}

export default function Metamask(props: MetamaskProps) {
    const [count, setCount] = useState(props.start);
    async function getMetamaskBalance() {
        const providerURL = props.prviderURL;
        const provider = new ethers.providers.JsonRpcProvider({
            url: providerURL
        });
        const balance = await provider.getBalance("<MY ADDRESS>");
        setCount(balance.toString());
    }
    return (
        <div class={tw`flex gap-2 w-full`}>
            <p class={tw`flex-grow-1 font-bold text-xl`}>{count}</p>
            <Button onClick={getMetamaskBalance}>Get Balance</Button>
    </div>
    );
}
```

**Comment by ntrotner** [comment]
The edge case for running this library in an environment that evaluates `isNode` or `isRN` is new to me, as we intended to use it in a Deno environment only.
I would suggest that you either use `ethers`, as the transpilation to Deno has been improved, or rewrite the `helpers.js` to only use the else case.

**Comment by bkosm** [comment]
@ntrotner thanks for responding. Do you suggest opening a pull request or do you consider this to be a local or version specific error?

**Comment by ntrotner** [comment]
Feel free to open a PR. However, you will face further issues (like using the HTTP provider, which doesn't have a Node equivalent libraries in Deno), so I'd suggest to use ethers for now, until the transpilers figure out how to convert the Web3 library automatically. As far as I remember, it's more practical to use it for a frontend application, as the concept revolves around serving a single user, whereas Web3 tries to be an interface for an Ethereum node.

**Comment by michael-spengler** [comment]
sorry for my very late response. 

have been living a rather offline life during the last months. 

I invited you as co-maintainers - so feel free to correct things whenever you like.

**Comment by michael-spengler** [comment]
... closing this issue as it seems you found appropriate workarounds.
