### ISSUE TITLE
Error when 2+ requests made.

### ISSUE THREAD

**Issue by zhangweis** [distributed-ledger-technology/web3#40]
You'll get 'Uncaught (in promise) Error: Invalid JSON RPC response: "Could not determine request body size"'.
```import Web3 from 'https://deno.land/x/web3/mod.ts'

const providerURL = Deno.args[0]

const web3 = new Web3(new (Web3 as any).providers.HttpProvider(providerURL))

const balance = await (web3 as any).eth.getBalance("0x7a915e362353d72570dcf90aa5baa1c5b341c7aa")

console.log(`the balance is ${balance} wei`)
const transactionHash = "0x0d558d490c89fc94ddfebd284e39da5c1bcff15d18c4e9fd2eb37a202d20c703"

const transaction = (await web3.eth.getTransaction(transactionHash))

console.log(transaction)```

**Comment by ntrotner** [comment]
For the time being, using the HTTP module of Web3 is a mess when it comes to the integration into Deno.
When I was transpiling the modules I tried to use compatible libraries that promised to implement the exact interface that Node uses for their HTTP module, however they didn't work in Deno, as the interface wasn't the same. 

So, for now you are left to use WebSockets.

**Comment by michael-spengler** [comment]
closing this issue @ntrotner
