### ISSUE TITLE
Unable to import with Deno after version 0.4.3. Error: Uncaught SyntaxError: The requested module 'https://deno.land/x/web3@v0.6.0/mod.ts' does not provide an export named 'default'

### ISSUE THREAD

**Issue by cg219** [distributed-ledger-technology/web3#8]
I'm running Web3 on Deno and trying to use any version after 0.4.3 results in an error during import.

```
warning: Cannot load module "https://deno.land/x/web3@v0.6.0/mod.ts".
  If the source module contains only types, use `import type` and `export type` to import it instead.

error: Uncaught SyntaxError: The requested module 'https://deno.land/x/web3@v0.6.0/mod.ts' does not provide an export named 'default'
import Web3 from 'https://deno.land/x/web3@v0.6.0/mod.ts'
```

Code to Reproduce

`import Web3 from 'https://deno.land/x/web3@v0.6.0/mod.ts'`

Expected Result

Web3 should have the Web3 module

**Comment by ntrotner** [comment]
Hey, thanks for your bug report. 
But I can't reproduce it on my machine. Did you

**Comment by cg219** [comment]
> Hey, thanks for your bug report, but I can't reproduce it on my machine. Did you try to apply the `--reload` option when running Deno? It seems like it loads an old version of `mod.ts` , as we switched from `export type` to `// deno-types=...`

Yup. Im running on Deno 1.16.1 if that helps.

I'm running this repo https://github.com/cg219/solidity-tests

May have to replace the provider address if its different from yours when you run in (on line 6 of `Inbox.text.js`)

I'll try to see if I can delete my Deno cache, but running the command with --reload provides the same error

**Comment by ntrotner** [comment]
Interesting, running with `deno test --reload --allow-net --allow-read` works for me with both versions.
But I can image what may cause your issue, as we are declaring the imports of sub-modules without a version tag. I will keep you updated on the new release, which will address it.

**Comment by cg219** [comment]
Thanks so much!! I may try this on a different machine where I haven't used a previous version on and see if I get the same error. Are you also running Deno 1.16.1 ??

**Comment by ntrotner** [comment]
I'm using 1.15.1

**Comment by ntrotner** [comment]
We published a new version with explicit versioning, so you could try to import it with
```
import Web3 from 'https://deno.land/x/web3@v0.7.1/mod.ts'
```

**Comment by cg219** [comment]
> We published a new version with explicit versioning, so you could try to import it with
> 
> ```
> import Web3 from 'https://deno.land/x/web3@v0.7.1/mod.ts'
> ```

Updated the code to pull version `0.7.1` and I now get a different error

```
error: Remote modules are not allowed to import local modules. Consider using a dynamic import instead.
  Importing: node:stream
    at https://deno.land/x/web3@v0.7.1/types/net.d.ts:16:29
```

**Comment by ntrotner** [comment]
Great catch, I updated the missing import on `v0.7.3`

**Comment by cg219** [comment]
> Great catch, I updated the missing import on `v0.7.3`

Worked!! All is well now :D
